import { useHome } from './logic'
import { HomeStyle } from './styles'

import MultiStepForm from 'components/organisms/MultiStepForm'

import type { TNextPageWithLayout } from 'typescript/next.types'

import Head from 'next/head'

const Home: TNextPageWithLayout = () => {
  const { onMultiStepFormSubmit, steps } = useHome()

  return (
    <>
      <Head>
        <title>Home</title>

        <meta name='description' content='Generated by create next app' />

        <link rel='icon' href='/favicon.ico' />
      </Head>

      <HomeStyle>
        <MultiStepForm steps={steps} onSubmit={onMultiStepFormSubmit} />
      </HomeStyle>
    </>
  )
}

export default Home
