import { useHome } from './logic'
import { HomeStyle } from './styles'

import MultiStepForm from 'components/organisms/MultiStepForm'

import type { TNextPageWithLayout } from 'typescript/next.types'

import Head from 'next/head'

const Home: TNextPageWithLayout = () => {
  const { onMultiStepFormSubmit, steps, initialStep, userInfo } = useHome()

  return (
    <>
      <Head>
        <title>Home</title>

        <meta name='description' content='Generated by create next app' />

        <link rel='icon' href='/favicon.ico' />
      </Head>

      <HomeStyle>
        <section>
          <MultiStepForm
            steps={steps}
            initialStep={initialStep}
            sessionKey='signup-multistep'
            onSubmit={onMultiStepFormSubmit}
          />
        </section>

        {userInfo && (
          <section>
            <ul>
              {userInfo.map(
                info =>
                  info[1] && (
                    <li key={info[0]}>
                      <span>{info[0]}:</span>
                      <b>{info[1]}</b>
                    </li>
                  )
              )}
            </ul>
          </section>
        )}
      </HomeStyle>
    </>
  )
}

export default Home
